feat: Added support for ENVS
OctopusDeploy/run-runbook-action pull request #250
Opened 2022-07-12 01:45 UTC by domenicsim1

feat: remove unused tags

2022-07-13 23:25 UTC, borland requested changes
Minor comments, but I want to resolve why there's the 2500ms sleep in the integration test

2022-07-13 23:25 UTC, borland commented on __tests__/integration/integration.test.ts
> +    globalCleanup.add(async () => repository.projects.del(project))
the `del` method returns a Promise already, so should be able to remove the async

`globalCleanup.add(() => repository.projects.del(project))`

2022-07-13 23:25 UTC, borland commented on __tests__/integration/integration.test.ts
> +    globalCleanup.add(async () => repository.runbooks.del(runbook))
as above can drop async lambda

2022-07-13 23:25 UTC, borland commented on __tests__/integration/integration.test.ts
> +    globalCleanup.add(async () => new Promise(r => setTimeout(r, 2500)))
? why is there a 2.5 second sleep here? Also async lambda shouldn't be neccessary

2022-07-13 23:25 UTC, borland commented on __tests__/integration/integration.test.ts
> +    // expectMatchAll(messages, [
Suggest removing this commented-out code and replace with a comment explaining that the output is variable and we can't really assert on it

2022-07-14 01:18 UTC, jbristowe approved these changes

2022-07-14 02:02 UTC, borland approved these changes

2022-07-14 02:14 UTC, merged